=begin
Create SDL_SCANCODE_* int to string table from SDL_scancode.h
SDL_GetScancodeName() returns environment-dependent names.
This file creates fixed name table from C symbol names.
Usage: ruby scancode.rb < /usr/include/SDL2/SDL_scancode.h > output.h
=end

CODE_NUM = 256
table = []

$stdin.each_line do |line|
	if /SDL_SCANCODE_(?<name>\w+)\s*=\s*(?<code>\d+)/ =~ line then
		name = Regexp.last_match[:name]
		code = Regexp.last_match[:code].to_i
		table[code] = name
	end
end

# delete SDL_SCANCODE_UNKNOWN
table[0] = nil

print <<"EOS"
// Auto generated by #{__FILE__}

#pragma once

#include <array>

namespace {

const std::array<const char *, #{CODE_NUM}> ScanCodeNames = {
EOS

CODE_NUM.times do |i|
	table[i] ||= ""
	puts "\t\"#{table[i]}\","
end

print <<EOS
};

}
EOS
